### ISSUE TITLE
"configsource.consul.host" does not work in Quarkus

### ISSUE THREAD

**Issue by 15I** [rikcarve/mp-config-consul#7]
"configsource.consul.host" does not work in Quarkus, but "configsource.consul.hosts" works with a single server. 
Is it possible make it like:

configsource.consul.host=192.168.99.100
and 
configsource.consul.host=failover:(192.168.99.100,192.168.99.101)

**Comment by rikcarve** [comment]
Tried to reproduce:
`docker run -d -p 8500:8500 --name=consul  consul`
check consul:
`curl localhost:8500/v1/status/peers`
should return localhost as well (client ip of consul, which must be reachable from your app)
`[
    "127.0.0.1:8300"
]`
Started quarkus:
`mvn clean compile quarkus:dev -Dconfigsource.consul.host=localhost`

resulted in:
`2020-04-13 10:05:14,065 INFO  [io.quarkus] (main) quarkus 1.0-SNAPSHOT (powered by Quarkus 1.3.2.Final) started in 5.559s. Listening on: http://0.0.0.0:8080`

Note: I had the same problem as you before, but then I realized, that consul returned a docker internal ip address when calling /status/peers (something like 172.17.0.2)

**Comment by 15I** [comment]
To reproduce:
run consul on host 192.168.99.100
start quarkus container on host 192.168.99.110 

mvn clean compile quarkus:dev -Dconfigsource.consul.host=192.168.99.100
----------------------Log Start ------------------------------
Listening for transport dt_socket at address: 5005
----------------------Log End------------------------------
Note: Quarkus container cannot start.

mvn clean compile quarkus:dev -Dconfigsource.consul.hosts=192.168.99.100
----------------------Log Start-----------------------
Listening for transport dt_socket at address: 5005
2020-04-13 19:15:26,307 INFO  [ch.car.mic.con.con.ConsulClientWrapper] (main) Successfully established connection to Consul. Current cluster leader is 172.21.0.17:8300
...
-------------------------------------------------------
Note: Quarkus container starts.

**Comment by rikcarve** [comment]
> 2020-04-13 19:15:26,307 INFO [ch.car.mic.con.con.ConsulClientWrapper] (main) Successfully established connection to Consul. Current cluster leader is 172.21.0.17:8300

Are you sure your application container can connect to 172.21.0.17 ? If not, you need to tell consul, to use a different client address (something like CONSUL_CLIENT_INTERFACE = 192.168.99.100).

**Comment by 15I** [comment]
Confirmed. My application can connect and retrieve all configurations from consul.
